### ISSUE TITLE
podman pod generate fails on AlmaLinux 9

### ISSUE THREAD

**Issue by MonsieurCellophane** [containers/podlet#128] opened 2024-10-28 16:45 UTC
On Almalinux 9 podlet generation from existing pod always fails:
```
$ podman --version
podman version 4.9.4-rhel

$ podman pod create foo
fd5d732bb4ca284fb9b8ed78a1a2b531ad9250eeb1fa4f8be5e7465c2ca3f8e6

$ podlet generate pod foo

Error: 
   0: error creating Quadlet file(s) from an existing object
   1: error inspecting pod `foo`
   2: error deserializing from `podman pod inspect foo` output
   3: invalid type: map, expected a sequence

Location:
   src/cli/generate.rs:752

Podman Stdout:
   {
        "Id": "fd5d732bb4ca284fb9b8ed78a1a2b531ad9250eeb1fa4f8be5e7465c2ca3f8e6",
....
```

Expected result  is quadlet  generation. This also happens if pod has more containers in it.

**Comment by k9withabone** [comment] 2024-10-28 19:48
Duplicate of #94. Fixed with #111. Will be a part of the next release.

**Closed by k9withabone** 2024-10-28 19:48 UTC
