### ISSUE TITLE
podlet blows up with -1 ulimit specs (invalid type: integer `-1`, expected u64)

### ISSUE THREAD

**Issue by draeath** [containers/podlet#124] opened 2024-10-18 17:50 UTC
Consider the following compose example:
    
    version: '3'
    services:
      opensearch:
        image: "docker.io/opensearchproject/opensearch:2.15.0"
        environment:
          - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
          - "bootstrap.memory_lock=true"
          - "discovery.type=single-node"
          - "action.auto_create_index=false"
          - "plugins.security.ssl.http.enabled=false"
          - "plugins.security.disabled=true"
        ulimits:
          memlock:
            hard: -1
            soft: -1
          nofile:
            soft: 65536
            hard: 65536
        ports:
          - "9203:9200"
          - "9303:9300"
        restart: "on-failure"
        networks:
          - graylog
        volumes:
          - "/z01/opensearch:/usr/share/opensearch/data"
    
    networks:
      graylog:
        driver: "bridge"

The following is received when used with `podlet compose`:

    Error: 
       0: error converting compose file
       1: error reading compose file
       2: File `docker-compose.yml` is not a valid compose file
       3: services.opensearch.ulimits.memlock.hard: invalid type: integer `-1`, expected u64 at line 27 column 15
    
    Location:
       /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/podlet-0.3.0/src/cli/compose.rs:203

This is invalid behavior, `-1` is a valid specification for these. [The compose spec only states that it be an integer, not that it be unsigned.](https://github.com/compose-spec/compose-spec/blob/6f87f9328842307d33dc777ca243cf92acf7aea4/schema/compose-spec.json#L925-L944)

**Comment by draeath** [comment] 2024-10-18 18:40
If it's useful, when the value of `-1` is provided, the output ulimit in the systemd unit should be `infinity`

**Comment by k9withabone** [comment] 2024-10-18 20:13
Duplicate of #117. Fixed with k9withabone/compose_spec_rs#32 and #122 / 2cb00b7. Will be a part of the next release.

**Closed** 2024-10-18 20:14 UTC
Labels: duplicate
