### ISSUE TITLE
Handle env file

### ISSUE THREAD

**Issue by gdmn** [containers/podlet#87] opened 2024-06-06 13:18 UTC
Variables from `.env` file are currently ignored, quadlet generation from compose file using these variables fails.

E.g., Immich compose file with "${UPLOAD_LOCATION}/photos:/usr/src/app/upload" volume definition:

```
wget https://raw.githubusercontent.com/immich-app/immich/main/docker/docker-compose.yml

podlet compose docker-compose.yml 
Error: 
   0: error converting compose file
   1: error reading compose file
   2: File `docker-compose.prod.yml` is not a valid compose file
   3: services.immich-server.volumes[0]: error parsing volume source: error parsing volume identifier: invalid start character `$`, identifiers must start with an ASCII letter (a-z, A-Z) or digit (0-9) at line 14 column 9

Location:
   src/cli/compose.rs:203

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by k9withabone** [comment] 2024-06-06 13:40
Pretty sure this is a duplicate of #81, please correct me if I'm wrong.

**Closed by k9withabone** 2024-06-06 13:40 UTC
