### ISSUE TITLE
Error parsing Podman container command

### ISSUE THREAD

**Issue by DIDoS** [containers/podlet#121] opened 2024-10-12 08:41 UTC
The following error happens while generating from a podman container run as a systemd service 
```./podlet generate container plex
Error:
   0: error creating Quadlet file(s) from an existing object
   1: error parsing Podman container command from `["/usr/bin/podman", "run", "--cidfile=/run/container-plex.service.ctr-id", "--cgroups=no-conmon", "--rm", "--sdnotify=conmon", "--conmon-pidfile", "/run/container-plex.pid", "--replace", "-d", "--name", "plex", "--network=host", "--label", "io.containers.autoupdate=image", "--cpu-shares=800", "-p", "32400:32400/tcp", "-p", "3005:3005/tcp", "-p", "8324:8324/tcp", "-p", "32469:32469/tcp", "-p", "1900:1900/udp", "-p", "32410:32410/udp", "-p", "32412:32412/udp", "-p", "32413:32413/udp", "-p", "32414:32414/udp", "-e", "PLEX_CLAIM=claim-XXXXXXXXXXXXXXXXXXXX", "-e", "TZ=Europe/XXXXX", "-e", "ADVERTISE_IP=http://192.168.0.99:32400/", "-h", "XXXX", "-v", "/opt/plex/config:/config", "-v", "/tmp/plex:/transcode", "-v", "/media/XXXXX1:/data", "-v", "/media/XXXXX2:/data2", "docker.io/plexinc/pms-docker:latest"]`
   2: [`Parser`] for container creation CLI options

   2: Usage: podlet [OPTIONS] <IMAGE> [COMMAND]...

   2: Options:
        -h, --help  Print help (see more with '--help')

   2: Podman Global Options:
            --cgroup-manager <MANAGER>                                     Cgroup manager to use [possible values: cgroupfs, systemd]
            --config <PATH>                                                Location of the authentication config file
            --conmon <PATH>                                                Path of the conmon binary
            --connection <CONNECTION_URI>                                  Connection to use for remote Podman service
            --events-backend <TYPE>                                        Backend to use for storing events [possible values: file, journald, none]
            --hooks-dir <PATH>                                             Set the OCI hooks directory path
            --identity <PATH>                                              Path to ssh identity file
            --imagestore <PATH>                                            Path to the 'image store'
            --log-level <LEVEL>                                            Log messages at and above specified level [default: warn] [possible values: debug, info, warn, error, fatal, panic]
            --module <PATH>                                                Load the specified `containers.conf(5)` module
            --network-cmd-path <PATH>                                      Path to the `slirp4netns(1)` command binary
            --network-config-dir <DIRECTORY>                               Path of the configuration directory for networks
            --out <PATH>                                                   Redirect the output of Podman to a file without affecting the container output or its logs
        -r, --remote[=<REMOTE>]                                            Access remote Podman service [possible values: true, false]
            --root <VALUE>                                                 Path to the graph root directory where images, containers, etc. are stored
            --runroot <VALUE>                                              Storage state directory where all state information is stored
            --runtime <VALUE>                                              Path to the OCI-compatible binary used to run containers
            --runtime-flag <FLAG>                                          Add global flags for the container runtime
            --ssh <VALUE>                                                  Define the ssh mode [possible values: golang, native]
            --storage-driver <VALUE>                                       Select which storage driver is used to manage storage of images and containers
            --storage-opt <VALUE>                                          Specify a storage driver option
            --syslog                                                       Output logging information to syslog as well as the console
            --tmpdir <PATH>                                                Path to the tmp directory for libpod state content
            --transient-store[=<TRANSIENT_STORE>]                          Enable transient container storage [possible values: true, false]
            --url <VALUE>                                                  URL to access Podman service
            --volumepath <VALUE>                                           Volume directory where builtin volume information is stored
            --cap-add <CAPABILITY>                                         Add Linux capabilities
            --device <HOST-DEVICE[:CONTAINER-DEVICE][:PERMISSIONS]>        Add a device node from the host into the container
            --annotation <KEY=VALUE>                                       Add an annotation to the container
            --name <NAME>                                                  The (optional) name of the container
            --dns <IP_ADDRESS>                                             Set custom DNS servers
            --dns-option <OPTION>                                          Set custom DNS options
            --dns-search <DOMAIN>                                          Set custom DNS search domains
            --cap-drop <CAPABILITY>                                        Drop Linux capability from the default Podman capability set
            --entrypoint <"COMMAND" | '["COMMAND", "ARG1", ...]'>          Override the default entrypoint of the image
        -e, --env <ENV>                                                    Set environment variables in the container
            --env-file <FILE>                                              Read in a line-delimited file of environment variables
            --env-host                                                     Use the host environment in the container
            --expose <PORT>                                                Exposes a port, or a range of ports, from the host to the container
            --gidmap <[FLAGS]CONTAINER_GID:FROM_GID[:AMOUNT]>              Run the container in a new user namespace using the supplied GID mapping
            --health-cmd <COMMAND>                                         Set or alter a healthcheck command for the container
            --health-interval <INTERVAL>                                   Set an interval for the healthchecks
            --health-on-failure <ACTION>                                   Action to take once the container transitions to an unhealthy state
            --health-retries <RETRIES>                                     The number of retries allowed before a healthcheck is considered unhealthy
            --health-start-period <PERIOD>                                 The initialization time needed for the container to bootstrap
            --health-startup-cmd <COMMAND>                                 Set a startup healthcheck command for the container
            --health-startup-interval <INTERVAL>                           Set an interval for the startup healthcheck
            --health-startup-retries <RETRIES>                             The number of retries allowed before the startup healthcheck restarts the container
            --health-startup-success <RETRIES>                             The number of successful runs required before the startup healthcheck will succeed
            --health-startup-timeout <TIMEOUT>                             The maximum time a startup healthcheck has to complete
            --health-timeout <TIMEOUT>                                     The maximum time a healthcheck has to complete
            --hostname <NAME>                                              Set the host name that is available inside the container
            --ip <IPV4>                                                    Specify a static IPv4 address for the container
            --ip6 <IPV6>                                                   Specify a static IPv6 address for the container
        -l, --label <KEY=VALUE>                                            Set one or more OCI labels on the container
            --log-driver <DRIVER>                                          Logging driver for the container
            --mount <type=TYPE,TYPE-SPECIFIC-OPTION[,...]>                 Attach a filesystem mount to the container
            --network <MODE>                                               Specify a custom network for the container [aliases: net]
            --sdnotify <SDNOTIFY>                                          Control sd-notify behavior [default: conmon] [possible values: conmon, container, healthy]
            --pids-limit <LIMIT>                                           Tune the container’s pids limit
        -p, --publish <[[IP:][HOST_PORT]:]CONTAINER_PORT[/PROTOCOL]>       Publish a container's port, or a range of ports, to the host
            --pull <POLICY>                                                Pull image policy [possible values: always, missing, never, newer]
            --read-only                                                    Mount the container's root filesystem as read-only
            --read-only-tmpfs <READ_ONLY_TMPFS>                            When running containers in read-only mode mount a read-write tmpfs on `/dev`, `/dev/shm`, `/run`, `/tmp`, and `/var/tmp` [default: true]
                                                                           [possible values: true, false]
            --rootfs <PATH[:OPTIONS]>                                      The rootfs to use for the container
            --init                                                         Run an init inside the container
            --secret <SECRET[,OPT=OPT,...]>                                Give the container access to a secret
            --shm-size <NUMBER[UNIT]>                                      Size of /dev/shm
            --stop-timeout <SECONDS>                                       Timeout to stop a container
            --subgidname <NAME>                                            Name of range listed in /etc/subgid for use in user namespace
            --subuidname <NAME>                                            Name of range listed in /etc/subuid for use in user namespace
            --sysctl <NAME=VALUE>                                          Configures namespaced kernel parameters for the container
            --tz <TIMEZONE>                                                Set the timezone in the container
            --tmpfs <FS>                                                   Create a tmpfs mount
            --uidmap <[FLAGS]CONTAINER_UID:FROM_UID[:AMOUNT]>              Run the container in a new user namespace using the supplied UID mapping
            --ulimit <OPTION>                                              Ulimit options; set the ulimit values inside of the container
        -u, --user <UID[:GID]>                                             Set the UID and, optionally, the GID used in the container
            --userns <MODE>                                                Set the user namespace mode for the container
        -v, --volume <[[SOURCE-VOLUME|HOST-DIR:]CONTAINER-DIR[:OPTIONS]]>  Mount a volume in the container
        -w, --workdir <DIR>                                                Working directory inside the container
            --add-host <HOST:IP>                                           Add a custom host-to-IP mapping
            --arch <ARCH>                                                  Override the architecture of the image to be pulled
        -a, --attach <STDIN | STDOUT | STDERR>                             Attach to STDIN, STDOUT, or STDERR
            --authfile <PATH>                                              Path of the authentication file
            --blkio-weight <WEIGHT>                                        Block IO relative weight, between 10 and 1000
            --blkio-weight-device <DEVICE:WEIGHT>                          Block IO relative device weight
            --cgroup-conf <KEY=VALUE>                                      Specify the cgroup file to write to and its value
            --cgroup-parent <PATH>                                         Path to cgroups under which the cgroup for the container will be created
            --cgroupns <MODE>                                              Set the cgroup namespace for the container
            --cgroups <HOW>                                                Whether the container will create cgroups
            --chrootdirs <PATH>                                            Chroot directories inside the container
            --cidfile <FILE>                                               Write container ID to a file
            --conmon-pidfile <FILE>                                        Write the pid of the conmon process to a file
            --cpu-period <LIMIT>                                           Limit the CPU CFS (Completely Fair Scheduler) period
            --cpu-quota <LIMIT>                                            Limit the CPU CFS (Completely Fair Scheduler) quota
            --cpu-rt-period <MICROSECONDS>                                 Limit the CPU real-time period in microseconds
            --cpu-rt-runtime <MICROSECONDS>                                Limit the CPU real-time runtime in microseconds
        -c, --cpu-shares <SHARES>                                          CPU shares (relative weight)
            --cpus <NUMBER>                                                Number of CPUs
            --cpuset-cpus <NUMBER>                                         CPUs in which to allow execution
            --cpuset-mems <NODES>                                          Memory nodes (MEMs) in which to allow execution
            --decryption-key <KEY[:PASSPHRASE]>                            Key needed to decrypt the image
        -d, --detach                                                       Detached mode: run the container in the background
            --detach-keys <SEQUENCE>                                       Key sequence for detaching a container
            --device-cgroup-rule <TYPE MAJOR:MINOR MODE>                   Add a rule to the cgroup allowed devices list
            --device-read-bps <PATH:RATE>                                  Limit read rate (in bytes per second) from a device
            --device-read-iops <PATH:RATE>                                 Limit read rate (in IO operations per second) from a device
            --device-write-bps <PATH:RATE>                                 Limit write rate (in bytes per second) to a device
            --device-write-iops <PATH:RATE>                                Limit write rate (in IO operations per second) to a device
            --disable-content-trust                                        This is a Docker specific option and is a NOOP
            --env-merge <ENV>                                              Preprocess default environment variables for the container
            --gpus <ENTRY>                                                 GPU devices to add to the container (`all` to pass all GPUs)
            --group-add <GROUP>                                            Assign additional groups to the primary user running within the container process
            --group-entry <ENTRY>                                          Customize the entry that is written to the /etc/group file within the container
            --hostuser <NAME>                                              Add a user account to /etc/passwd from the host to the container
            --http-proxy <HTTP_PROXY>                                      Set proxy environment variables in the container based on the host proxy vars [default: true] [possible values: true, false]
            --image-volume <bind | tmpfs | ignore>                         How to handle the builtin image volumes
            --init-path <PATH>                                             Path to the container-init binary
        -i, --interactive                                                  keep stdin open even if not attached
            --ipc <IPC>                                                    Set the IPC namespace mode for the container
            --label-file <FILE>                                            Read in a line-delimited file of labels
            --link-local-ip <IP>                                           Not implemented
            --log-opt <NAME=VALUE>                                         Logging driver specific options
            --mac-address <ADDRESS>                                        Container network interface MAC address
        -m, --memory <NUMBER[UNIT]>                                        Memory limit
            --memory-reservation <NUMBER[UNIT]>                            Memory soft limit
            --memory-swap <NUMBER[UNIT]>                                   Limit value equal to memory plus swap
            --memory-swappiness <NUMBER>                                   Tune the container’s memory swappiness behavior
            --network-alias <ALIAS>                                        Add a network-scoped alias for the container
            --no-healthcheck                                               Disable healthchecks on the container
            --no-hosts                                                     Do not create /etc/hosts for the container
            --oom-kill-disable                                             Disable OOM Killer for the container
            --oom-score-adj <NUM>                                          Tune the host’s OOM preferences for the container
            --os <OS>                                                      Override the OS, defaults to hosts, of the image to be pulled
            --passwd                                                       Add entries to /etc/passwd and /etc/group when used with the --user option
            --passwd-entry <ENTRY>                                         Entry to write to /etc/passwd
            --personality <PERSONA>                                        Configure execution domain using personality
            --pid <MODE>                                                   Set the PID namespace mode for the container
            --pidfile <PATH>                                               Write the container process ID to the file
            --platform <OS/ARCH>                                           Specify the platform for selecting the image
            --pod <NAME>                                                   Run the container in an existing pod
            --pod-id-file <FILE>                                           Read the pod ID from the file
            --preserve-fd <FD1[,FD2,…]>                                    Pass down to the process additional file descriptors
            --preserve-fds <N>                                             Pass a number of additional file descriptors into the container
            --privileged                                                   Give extended privileges to the container
        -P, --publish-all                                                  Publish all exposed ports to random ports on the host interfaces
        -q, --quiet                                                        Suppress output information when pulling images
            --replace                                                      If a container with the same name exists, replace it
            --requires <CONTAINER[,...]>                                   Add one or more requirement containers
            --retry <ATTEMPTS>                                             Number of times to retry pulling or pushing images between the registry and local storage
            --retry-delay <DURATION>                                       Duration of delay between retry attempts when pulling or pushing images
            --rm                                                           Remove container (and pod if created) after exit
            --rmi                                                          After the container exits, remove the container image unless it is used by other containers
            --seccomp-policy <POLICY>                                      Specify the policy to select the seccomp profile
            --shm-size-systemd <NUMBER[UNIT]>                              Size of systemd-specific tmpfs mounts: /run, /run/lock, /var/log/journal, and /tmp
            --sig-proxy <SIG_PROXY>                                        Proxy received signals to the container process [default: true] [possible values: true, false]
            --stop-signal <SIGNAL>                                         Signal to stop a container
            --systemd <true | false | always>                              Run container in systemd mode
            --timeout <SECONDS>                                            Maximum length of time a container is allowed to run
            --tls-verify[=<TLS_VERIFY>]                                    Require HTTPS and verify certificates when contacting registries [possible values: true, false]
        -t, --tty                                                          Allocate a pseudo-TTY
            --umask <UMASK>                                                Set the umask inside the container
            --uts <MODE>                                                   Set the UTS namespace mode for the container
            --variant <VARIANT>                                            Set variant to use instead of the default architecture variant of the container image
            --volumes-from <CONTAINER[:OPTIONS]>                           Mount volumes from the specified container
            --security-opt <OPTION>                                        Security options
            --restart <POLICY>                                             Configure if and when the service should be restarted [possible values: no, on-success, on-failure, on-abnormal, on-watchdog, on-abort,
                                                                           always]
        [COMMAND]...                                                   Optionally, the command to run in the container
        <IMAGE>                                                        The image to run in the container
   2:

Location:
   src/cli/generate.rs:152

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Here is the inspected container 
```podman inspect plex
[
     {
          "Id": "6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384",
          "Created": "2024-10-12T09:03:38.112735845+02:00",
          "Path": "/init",
          "Args": [
               "/init"
          ],
          "State": {
               "OciVersion": "1.1.0",
               "Status": "running",
               "Running": true,
               "Paused": false,
               "Restarting": false,
               "OOMKilled": false,
               "Dead": false,
               "Pid": 2390,
               "ConmonPid": 2347,
               "ExitCode": 0,
               "Error": "",
               "StartedAt": "2024-10-12T09:03:38.352293389+02:00",
               "FinishedAt": "0001-01-01T00:00:00Z",
               "Health": {
                    "Status": "healthy",
                    "FailingStreak": 0,
                    "Log": [
                         {
                              "Start": "2024-10-12T10:22:55.783117336+02:00",
                              "End": "2024-10-12T10:22:55.889397083+02:00",
                              "ExitCode": 0,
                              "Output": ""
                         },
                         {
                              "Start": "2024-10-12T10:23:01.777440195+02:00",
                              "End": "2024-10-12T10:23:01.877778942+02:00",
                              "ExitCode": 0,
                              "Output": ""
                         },
                         {
                              "Start": "2024-10-12T10:23:07.779065482+02:00",
                              "End": "2024-10-12T10:23:07.892550246+02:00",
                              "ExitCode": 0,
                              "Output": ""
                         },
                         {
                              "Start": "2024-10-12T10:23:13.779589608+02:00",
                              "End": "2024-10-12T10:23:13.866096498+02:00",
                              "ExitCode": 0,
                              "Output": ""
                         },
                         {
                              "Start": "2024-10-12T10:23:19.783840287+02:00",
                              "End": "2024-10-12T10:23:19.86384461+02:00",
                              "ExitCode": 0,
                              "Output": ""
                         }
                    ]
               },
               "CgroupPath": "/machine.slice/libpod-6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384.scope",
               "CheckpointedAt": "0001-01-01T00:00:00Z",
               "RestoredAt": "0001-01-01T00:00:00Z"
          },
          "Image": "c97f94aa96ac79a71328ec790c260f972b5746756d9ee35262f663d320f99cb6",
          "ImageDigest": "sha256:d55135de7cc93bb844e09dc0efb8b1eccb655b4ea8741945163de1163df5e043",
          "ImageName": "docker.io/plexinc/pms-docker:latest",
          "Rootfs": "",
          "Pod": "",
          "ResolvConfPath": "/run/containers/storage/overlay-containers/6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384/userdata/resolv.conf",
          "HostnamePath": "/run/containers/storage/overlay-containers/6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384/userdata/hostname",
          "HostsPath": "/run/containers/storage/overlay-containers/6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384/userdata/hosts",
          "StaticDir": "/var/lib/containers/storage/overlay-containers/6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384/userdata",
          "OCIConfigPath": "/var/lib/containers/storage/overlay-containers/6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384/userdata/config.json",
          "OCIRuntime": "runc",
          "ConmonPidFile": "/run/container-plex.pid",
          "PidFile": "/run/containers/storage/overlay-containers/6ee993b6eeaa2f8d12f3a26126788cb418930ddb2c1d41db4fd28296c4409384/userdata/pidfile",
          "Name": "plex",
          "RestartCount": 0,
          "Driver": "overlay",
          "MountLabel": "",
          "ProcessLabel": "",
          "AppArmorProfile": "containers-default-0.57.4",
          "EffectiveCaps": [
               "CAP_CHOWN",
               "CAP_DAC_OVERRIDE",
               "CAP_FOWNER",
               "CAP_FSETID",
               "CAP_KILL",
               "CAP_NET_BIND_SERVICE",
               "CAP_SETFCAP",
               "CAP_SETGID",
               "CAP_SETPCAP",
               "CAP_SETUID",
               "CAP_SYS_CHROOT"
          ],
          "BoundingCaps": [
               "CAP_CHOWN",
               "CAP_DAC_OVERRIDE",
               "CAP_FOWNER",
               "CAP_FSETID",
               "CAP_KILL",
               "CAP_NET_BIND_SERVICE",
               "CAP_SETFCAP",
               "CAP_SETGID",
               "CAP_SETPCAP",
               "CAP_SETUID",
               "CAP_SYS_CHROOT"
          ],
          "ExecIDs": [],
          "GraphDriver": {
               "Name": "overlay",
               "Data": {
                    "LowerDir": "/var/lib/containers/storage/overlay/430dddfc2892b8f6c7c86e5ba60a1c9ad71d634450ef023323844f577a04d1fa/diff:/var/lib/containers/storage/overlay/3500ca859a77c7d9ecf3b9e77f1b8c934ee6a1d8580c908945c3a9e37b8c15ac/diff:/var/lib/containers/storage/overlay/e4e302091d268b7d1615959fd87fca5f6f8029ba8d11482bb11225cd6832c664/diff:/var/lib/containers/storage/overlay/17b380b1f7717dd0c5faab5506a6d3d1cfb563d20a079650cf748212ddb49b5c/diff:/var/lib/containers/storage/overlay/33234515ca36e430156738f8571a8276db6e74fe30d5dbbb037220bd81bb18f5/diff:/var/lib/containers/storage/overlay/3ec3ded77c0ce89e931f92aed086b2a2c774a6fbd51617853decc8afa4e1087a/diff",
                    "MergedDir": "/var/lib/containers/storage/overlay/5e2be1df3dfa91c02a74ad1f308d302e45acdd78e726cf47f1c186fff601aa13/merged",
                    "UpperDir": "/var/lib/containers/storage/overlay/5e2be1df3dfa91c02a74ad1f308d302e45acdd78e726cf47f1c186fff601aa13/diff",
                    "WorkDir": "/var/lib/containers/storage/overlay/5e2be1df3dfa91c02a74ad1f308d302e45acdd78e726cf47f1c186fff601aa13/work"
               }
          },
          "Mounts": [
               {
                    "Type": "bind",
                    "Source": "/media/XXXXX2",
                    "Destination": "/data2",
                    "Driver": "",
                    "Mode": "",
                    "Options": [
                         "rbind"
                    ],
                    "RW": true,
                    "Propagation": "rprivate"
               },
               {
                    "Type": "bind",
                    "Source": "/opt/plex/config",
                    "Destination": "/config",
                    "Driver": "",
                    "Mode": "",
                    "Options": [
                         "rbind"
                    ],
                    "RW": true,
                    "Propagation": "rprivate"
               },
               {
                    "Type": "bind",
                    "Source": "/tmp/plex",
                    "Destination": "/transcode",
                    "Driver": "",
                    "Mode": "",
                    "Options": [
                         "rbind"
                    ],
                    "RW": true,
                    "Propagation": "rprivate"
               },
               {
                    "Type": "bind",
                    "Source": "/media/XXXXX1",
                    "Destination": "/data",
                    "Driver": "",
                    "Mode": "",
                    "Options": [
                         "rbind"
                    ],
                    "RW": true,
                    "Propagation": "rprivate"
               }
          ],
          "Dependencies": [],
          "NetworkSettings": {
               "EndpointID": "",
               "Gateway": "",
               "IPAddress": "",
               "IPPrefixLen": 0,
               "IPv6Gateway": "",
               "GlobalIPv6Address": "",
               "GlobalIPv6PrefixLen": 0,
               "MacAddress": "",
               "Bridge": "",
               "SandboxID": "",
               "HairpinMode": false,
               "LinkLocalIPv6Address": "",
               "LinkLocalIPv6PrefixLen": 0,
               "Ports": {},
               "SandboxKey": "",
               "Networks": {
                    "host": {
                         "EndpointID": "",
                         "Gateway": "",
                         "IPAddress": "",
                         "IPPrefixLen": 0,
                         "IPv6Gateway": "",
                         "GlobalIPv6Address": "",
                         "GlobalIPv6PrefixLen": 0,
                         "MacAddress": "",
                         "NetworkID": "host",
                         "DriverOpts": null,
                         "IPAMConfig": null,
                         "Links": null
                    }
               }
          },
          "Namespace": "",
          "IsInfra": false,
          "IsService": false,
          "KubeExitCodePropagation": "invalid",
          "lockNumber": 1,
          "Config": {
               "Hostname": "XXXX",
               "Domainname": "",
               "User": "",
               "AttachStdin": false,
               "AttachStdout": false,
               "AttachStderr": false,
               "Tty": false,
               "OpenStdin": false,
               "StdinOnce": false,
               "Env": [
                    "LANG=C.UTF-8",
                    "CHANGE_CONFIG_DIR_OWNERSHIP=true",
                    "HOME=/config",
                    "ADVERTISE_IP=http://192.168.0.99:32400/",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "container=podman",
                    "TERM=xterm",
                    "LC_ALL=C.UTF-8",
                    "PLEX_CLAIM=claim-XXXXXXXXXXXXXXXXXXXX",
                    "TZ=Europe/XXXXX",
                    "HOSTNAME=XXXX"
               ],
               "Cmd": null,
               "Image": "docker.io/plexinc/pms-docker:latest",
               "Volumes": null,
               "WorkingDir": "/",
               "Entrypoint": "/init",
               "OnBuild": null,
               "Labels": {
                    "PODMAN_SYSTEMD_UNIT": "container-plex.service",
                    "io.containers.autoupdate": "image",
                    "org.opencontainers.image.created": "2024-09-11T16:25:53.185Z",
                    "org.opencontainers.image.description": "\"The Plex Media Server\"",
                    "org.opencontainers.image.licenses": "NOASSERTION",
                    "org.opencontainers.image.ref.name": "ubuntu",
                    "org.opencontainers.image.revision": "c8e17655441744e88dd3b45f96f824052fda79a3",
                    "org.opencontainers.image.source": "https://github.com/plexinc/pms-docker",
                    "org.opencontainers.image.title": "Plex Media Server",
                    "org.opencontainers.image.url": "https://github.com/plexinc/plex-media-server",
                    "org.opencontainers.image.vendor": "Plex, GmbH",
                    "org.opencontainers.image.version": "1.41.0.8992-8463ad060"
               },
               "Annotations": {
                    "io.container.manager": "libpod",
                    "io.podman.annotations.autoremove": "TRUE",
                    "io.podman.annotations.cid-file": "/run/container-plex.service.ctr-id",
                    "org.opencontainers.image.stopSignal": "15"
               },
               "StopSignal": 15,
               "Healthcheck": {
                    "Test": [
                         "CMD-SHELL",
                         "/healthcheck.sh || exit 1"
                    ],
                    "Interval": 5000000000,
                    "Timeout": 2000000000,
                    "Retries": 20
               },
               "HealthcheckOnFailureAction": "none",
               "CreateCommand": [
                    "/usr/bin/podman",
                    "run",
                    "--cidfile=/run/container-plex.service.ctr-id",
                    "--cgroups=no-conmon",
                    "--rm",
                    "--sdnotify=conmon",
                    "--conmon-pidfile",
                    "/run/container-plex.pid",
                    "--replace",
                    "-d",
                    "--name",
                    "plex",
                    "--network=host",
                    "--label",
                    "io.containers.autoupdate=image",
                    "--cpu-shares=800",
                    "-p",
                    "32400:32400/tcp",
                    "-p",
                    "3005:3005/tcp",
                    "-p",
                    "8324:8324/tcp",
                    "-p",
                    "32469:32469/tcp",
                    "-p",
                    "1900:1900/udp",
                    "-p",
                    "32410:32410/udp",
                    "-p",
                    "32412:32412/udp",
                    "-p",
                    "32413:32413/udp",
                    "-p",
                    "32414:32414/udp",
                    "-e",
                    "PLEX_CLAIM=claim-XXXXXXXXXXXXXXXXXXXX",
                    "-e",
                    "TZ=Europe/Vienna",
                    "-e",
                    "ADVERTISE_IP=http://192.168.0.99:32400/",
                    "-h",
                    "XXXX",
                    "-v",
                    "/opt/plex/config:/config",
                    "-v",
                    "/tmp/plex:/transcode",
                    "-v",
                    "/media/XXXXX1:/data",
                    "-v",
                    "/media/XXXXX2:/data2",
                    "docker.io/plexinc/pms-docker:latest"
               ],
               "Umask": "0022",
               "Timeout": 0,
               "StopTimeout": 10,
               "Passwd": true,
               "sdNotifyMode": "conmon",
               "sdNotifySocket": "/run/systemd/notify"
          },
          "HostConfig": {
               "Binds": [
                    "/media/XXXXX2:/data2:rw,rprivate,rbind",
                    "/opt/plex/config:/config:rw,rprivate,rbind",
                    "/tmp/plex:/transcode:rw,rprivate,rbind",
                    "/media/XXXXX1:/data:rw,rprivate,rbind"
               ],
               "CgroupManager": "systemd",
               "CgroupMode": "private",
               "ContainerIDFile": "/run/container-plex.service.ctr-id",
               "LogConfig": {
                    "Type": "journald",
                    "Config": null,
                    "Path": "",
                    "Tag": "",
                    "Size": "0B"
               },
               "NetworkMode": "host",
               "PortBindings": {},
               "RestartPolicy": {
                    "Name": "",
                    "MaximumRetryCount": 0
               },
               "AutoRemove": true,
               "VolumeDriver": "",
               "VolumesFrom": null,
               "CapAdd": [],
               "CapDrop": [],
               "Dns": [],
               "DnsOptions": [],
               "DnsSearch": [],
               "ExtraHosts": [],
               "GroupAdd": [],
               "IpcMode": "shareable",
               "Cgroup": "",
               "Cgroups": "default",
               "Links": null,
               "OomScoreAdj": 0,
               "PidMode": "private",
               "Privileged": false,
               "PublishAllPorts": false,
               "ReadonlyRootfs": false,
               "SecurityOpt": [],
               "Tmpfs": {},
               "UTSMode": "private",
               "UsernsMode": "",
               "ShmSize": 65536000,
               "Runtime": "oci",
               "ConsoleSize": [
                    0,
                    0
               ],
               "Isolation": "",
               "CpuShares": 800,
               "Memory": 0,
               "NanoCpus": 0,
               "CgroupParent": "",
               "BlkioWeight": 0,
               "BlkioWeightDevice": null,
               "BlkioDeviceReadBps": null,
               "BlkioDeviceWriteBps": null,
               "BlkioDeviceReadIOps": null,
               "BlkioDeviceWriteIOps": null,
               "CpuPeriod": 0,
               "CpuQuota": 0,
               "CpuRealtimePeriod": 0,
               "CpuRealtimeRuntime": 0,
               "CpusetCpus": "",
               "CpusetMems": "",
               "Devices": [],
               "DiskQuota": 0,
               "KernelMemory": 0,
               "MemoryReservation": 0,
               "MemorySwap": 0,
               "MemorySwappiness": 0,
               "OomKillDisable": false,
               "PidsLimit": 2048,
               "Ulimits": [
                    {
                         "Name": "RLIMIT_NPROC",
                         "Soft": 4194304,
                         "Hard": 4194304
                    }
               ],
               "CpuCount": 0,
               "CpuPercent": 0,
               "IOMaximumIOps": 0,
               "IOMaximumBandwidth": 0,
               "CgroupConf": null
          }
     }
]
```

Versions: podlet 0.3.0
podman version 4.9.3

**Comment by k9withabone** [comment] 2024-10-12 11:27
Duplicate of #105.

**Closed by k9withabone** 2024-10-12 11:27 UTC
